# Generated by Django 3.2.4 on 2021-06-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('complaint', models.CharField(choices=[('M', 'Management'), ('E', 'Education'), ('D', 'Deployment'), ('S', 'Salary'), ('G', 'General')], default='G', max_length=1)),
                ('cohort', models.CharField(choices=[('P', 'Python'), ('J', 'Java'), ('R', 'React'), ('A', 'Android'), ('L', 'Linux'), ('C', 'Cybersecurity'), ('U', 'Unknown')], default='U', max_length=1)),
                ('level', models.CharField(choices=[('I', 'Individual'), ('G', 'General')], default='I', max_length=1)),
                ('description', models.TextField(max_length=500)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
