# Generated by Django 3.2.4 on 2021-06-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaints',
            new_name='complaint',
        ),
    ]
