# Generated by Django 3.2.4 on 2021-06-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_rename_complaints_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Resolved')], default='P', max_length=1),
        ),
    ]
