# Generated by Django 3.2.4 on 2021-06-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_auto_20210616_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resoultion',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
