# Generated by Django 3.2.4 on 2021-06-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.CharField(choices=[('M', 'Mentor'), ('T', 'Trainee')], default='T', max_length=1),
        ),
    ]
