# Generated by Django 3.2.4 on 2021-06-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint',
            new_name='complaint_for',
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_to',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Mentor')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
