# Generated by Django 3.2.4 on 2021-06-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_auto_20210614_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('N', 'Need Clarification'), ('R', 'Resolved')], default='P', max_length=1),
        ),
    ]
