# Generated by Django 3.2.4 on 2021-06-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('A', 'Anonymous'), ('I', 'Identifiable')], default='P', max_length=1),
        ),
    ]
