# Generated by Django 3.2.4 on 2021-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('A', 'Anonymous'), ('I', 'Identifiable')], default='I', max_length=1),
        ),
    ]
